name: Keep Render Service Alive

on:
  schedule:
    # Ping every 10 minutes during evaluation hours (9 AM to 6 PM IST)
    - cron: '*/10 9-18 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Render Service
      run: |
        echo "🚀 Pinging RAG Model service to keep it alive..."
        
        # Replace with your actual Render service URL
        SERVICE_URL="https://rag-model-api.onrender.com"
        HEALTH_URL="${SERVICE_URL}/health"
        
        response=$(curl -s -w "HTTPSTATUS:%{http_code};TIME:%{time_total}" "$HEALTH_URL")
        http_code=$(echo "$response" | sed -n 's/.*HTTPSTATUS:\([0-9]*\).*/\1/p')
        time_total=$(echo "$response" | sed -n 's/.*TIME:\([0-9.]*\).*/\1/p')
        
        if [ "$http_code" = "200" ]; then
          echo "✅ Service alive (Status: $http_code, Time: ${time_total}s)"
        else
          echo "⚠️ Service status: $http_code (Time: ${time_total}s)"
          exit 1
        fi
        
    - name: Notify on Failure
      if: failure()
      run: |
        echo "❌ Keep-alive check failed - service may be down"
